apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app-monolith
        image: dmpinero/todo-app-monolith
        envFrom:
        - configMapRef:
            name: todo-app-configmap
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
