apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistentvolumeclaim
  labels:
    app: todo-app-postgres
spec:
  storageClassName: postgres-storageclass
  resources:
    requests:
      storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

