apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-persistentvolume
  labels:
    app: todo-app-postgres
spec:
  storageClassName: postgres-storageclass
  volumeMode: Filesystem
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
      path: /var/lib/postgresql/data
