apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: todo-app-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: todo-app-postgres
